### ISSUE TITLE
Add a place holder text when no tracks are uploaded

### ISSUE THREAD

**Issue by neel1998** [enviroCar/enviroCar-app#454]
Currently the uploaded tracks screen is blank when there are no tracks uploaded. Adding a place holder text would be nice since blank screen doesnt look good and is confusing.

**Current State**

<img src="https://user-images.githubusercontent.com/32041242/75009841-a56be180-54a1-11ea-9be7-a481a33de565.jpg" height = 500/>

**I would like to work on this issue**

**Comment by asaikarthikeya** [comment]
fixed by commit - 02aeb0b

**Comment by cdhiraj40** [comment]
hey, @asaikarthikeya I still see this happening. I updated from the repo and tried. I recently downloaded it on another directory and tried but it still shows me a blank screen

I have worked on it and it doesn't show a blank screen after my implementation. If you also see the blank screen then I would like to work on it.

**Comment by cdhiraj40** [comment]
before
https://user-images.githubusercontent.com/75211982/133569320-d9a1100b-c373-4a4f-bd7e-398b12e59d91.mp4

**Comment by cdhiraj40** [comment]
after:

https://user-images.githubusercontent.com/75211982/133569440-259a3749-c700-4fad-a1d7-30de5cb8fe11.mp4

**Comment by cdhiraj40** [comment]
@SebaDro  can you confirm about the 

> hey, @asaikarthikeya I still see this happening. I updated from the repo and tried. I recently downloaded it on another directory and tried but it still shows me a blank screen
> 
> I have worked on it and it doesn't show a blank screen after my implementation. If you also see the blank screen then I would like to work on it.

@SebaDro can you confirm this?

**Comment by asaikarthikeya** [comment]
You can work on this @cdhiraj40. Please make your PR with the relevant code changes. Thanks :)

**Comment by asaikarthikeya** [comment]
@SebaDro If i see understand the commit correctly, only displaying background image after an operation is handled in https://github.com/enviroCar/enviroCar-app/commit/02aeb0bbcaed2727ca23b442eea70400ee7e4a66. Tracks should be checked and background image should be set when upload track is opened. ;)

**Comment by SebaDro** [comment]
I was about to answer, that the described issue has been fixed in 02aeb0b, but you were just faster ;-). Actually, you're right. There is still a blank screen, when opening the uploaded tracks fragment second time. So, feel free to work on it

**Comment by cdhiraj40** [comment]
> I was about to answer, that the described issue has been fixed in [02aeb0b](https://github.com/enviroCar/enviroCar-app/commit/02aeb0bbcaed2727ca23b442eea70400ee7e4a66), but you were just faster ;-). Actually, you're right. There is still a blank screen, when opening the uploaded tracks fragment second time. So, feel free to work on it

I already did sir. Thanks :)

**Comment by asaikarthikeya** [comment]
> I was about to answer, that the described issue has been fixed in 02aeb0b, but you were just faster ;-). Actually, you're right. There is still a blank screen, when opening the uploaded tracks fragment second time. So, feel free to work on it

Yes, I have been following the code changes regularly and clearing the issues/PR the have been resolved ;)
